batch_size: 4
epochs: 1
lr: 0.001
profiler: null
criterion:
  _target_: torch.nn.L1Loss
accumulate_grad_batches: 1

fast_dev_run: true

trainer_logger: null
callbacks:
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: train_loss