epochs: 1
profiler: null
precision: 16-mixed
criterion:
  _target_: torch.nn.L1Loss
accumulate_grad_batches: 1

fast_dev_run: true

trainer_logger:
  null
  # _target_: lightning.pytorch.loggers.NeptuneLogger
  # project: aaa/bbb
  # api_key: xxx
  # log_model_checkpoints: true

callbacks:
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: train_loss
  # - _target_: lightning.pytorch.callbacks.BatchSizeFinder
  # - _target_: callback.discord.DiscordCallback
  #   webhook_url: xxx
