metadata_dir: "./data/FMA/fma_metadata"
audio_dir: "./data/FMA/fma_small"

batch_size: 4
epochs: 1
lr: 0.001
profiler: null
criterion:
  _target_: torch.nn.L1Loss

fast_dev_run: true

trainer_logger: null
model_logger: null
callbacks: null